import { useState, useEffect } from "react";
import { useForm } from "react-hook-form";
import { useParams } from "react-router-dom";
import { Form, FormField, FormItem, FormLabel, FormControl, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "@/components/ui/sonner";
import { transferService, MoneyTransfer } from "@/services/transferService";
import { employeeService, Employee } from "@/services/employeeService";
import { useToast } from "@/hooks/use-toast";

type TransferFormValues = {
  employeeId: string;
  amount: number;
  currency: string;
  destination: string;
  beneficiary_name: string;
  beneficiary_phone: string;
  notes?: string;
};

const currencies = ["USD", "EUR", "GBP", "AED", "SAR", "EGP"];

const TransferForm = () => {
  const { id } = useParams<{ id: string }>();
  const [employee, setEmployee] = useState<Employee | null>(null);
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();
  
  // Fetch employee data
  useEffect(() => {
    const fetchEmployee = async () => {
      if (!id) return;
      
      try {
        const data = await employeeService.getById(id);
        setEmployee(data);
      } catch (error) {
        console.error('Error fetching employee:', error);
      }
    };
    
    fetchEmployee();
  }, [id]);
  
  const form = useForm<TransferFormValues>({
    defaultValues: {
      employeeId: id || "",
      amount: 0,
      currency: "USD",
      destination: "",
      beneficiary_name: "",
      beneficiary_phone: "",
      notes: ""
    }
  });
  
  const onSubmit = async (values: TransferFormValues) => {
    if (!employee) return;
    
    setLoading(true);
    try {
      // Create a new transfer using the service
      await transferService.create({
        id: "", // This will be generated by the server
        employee_id: values.employeeId,
        employee_name: employee.name,
        amount: values.amount,
        currency: values.currency,
        destination: values.destination,
        beneficiary_name: values.beneficiary_name,
        beneficiary_phone: values.beneficiary_phone,
        notes: values.notes,
        status: 'Pending', // Initial status
        date: new Date().toISOString(),
        last_updated: new Date().toISOString()
      });
      
      toast({
        title: "Money transfer initiated",
        description: `Transfer of ${values.currency} ${values.amount} to ${values.beneficiary_name} has been initiated.`,
        variant: "default"
      });
      
      form.reset({
        employeeId: id || "",
        amount: 0,
        currency: "USD",
        destination: "",
        beneficiary_name: "",
        beneficiary_phone: "",
        notes: ""
      });
    } catch (error) {
      console.error('Error creating transfer:', error);
      toast({
        title: "Failed to initiate transfer",
        description: "There was an error processing your request. Please try again.",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };
  
  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <FormField
            control={form.control}
            name="amount"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Amount</FormLabel>
                <FormControl>
                  <Input
                    type="number"
                    placeholder="Enter amount"
                    {...field}
                    onChange={e => field.onChange(Number(e.target.value))}
                    required
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          
          <FormField
            control={form.control}
            name="currency"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Currency</FormLabel>
                <Select onValueChange={field.onChange} defaultValue={field.value}>
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Select currency" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    {currencies.map(currency => (
                      <SelectItem key={currency} value={currency}>
                        {currency}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <FormMessage />
              </FormItem>
            )}
          />
        </div>
        
        <FormField
          control={form.control}
          name="destination"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Destination Country</FormLabel>
              <FormControl>
                <Input placeholder="Enter destination country" {...field} required />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <FormField
            control={form.control}
            name="beneficiary_name"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Beneficiary Name</FormLabel>
                <FormControl>
                  <Input placeholder="Enter beneficiary name" {...field} required />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          
          <FormField
            control={form.control}
            name="beneficiary_phone"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Beneficiary Phone</FormLabel>
                <FormControl>
                  <Input placeholder="Enter beneficiary phone number" {...field} required />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
        </div>
        
        <FormField
          control={form.control}
          name="notes"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Notes</FormLabel>
              <FormControl>
                <Textarea placeholder="Enter any additional notes" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        
        <div className="flex justify-end">
          <Button type="submit" disabled={loading}>
            {loading ? "Processing..." : "Initiate Transfer"}
          </Button>
        </div>
      </form>
    </Form>
  );
};

export default TransferForm;
